ethersphere/swarm-guide

contents/runninganode.rst
including SWAP, mining and custom genesis block.
=> Updated installation instructions

README.md, contents/introduction.rst
I noticed some forward-ticks instead of back-ticks; I finished a sentence in a plausible way.
=> ReST markup

contents/runninganode.rst, contents/usage.rst
I updated and expanded the ENS section. 
It had to be updated anyway because it was still referring to the (now defunct) setHash and getHash functions. 
Having fought with ENS all day, I decided to make the documentation a little easier to follow.
=> updated ens section

contents/usage.rst
=> fix hyperlink syntax

contents/installation.rst, contents/runninganode.rst, contents/usage.rst
=> some small fixes and an ens addition.

contents/runninganode.rst
All the instructions to run a singleton swarm node + geth in one place!
=> Add convenience script

contents/installation.rst
This is a required flow for installation on Ubuntu 14.04. If you follow original instructions you have errors.
=> Installation prerequisites section update

contents/conf.py, contents/index.rst, contents/runninganode.rst, contents/simpleuser.rst
Users should not be bogged down by all the stuff they can configure. They need a simple page that tells them how to get to the gist of it which is interacting with Swarm. These improvement were made to address that.
=> Added toned down instruction set for users that do not require advanced customization.

contents/runninganode.rst
=> Replace the --ethapi flag with --ens-api and --swap-api

contents/architecture.rst, contents/installation.rst, contents/introduction.rst, contents/runninganode.rst, contents/simpleuser.rst, contents/usage.rst
Configuration parameters, general light overhaul, tar and form uploads
=> Updated documentation with new config parameter

contents/runninganode.rst
=> fix small typo

contents/installation.rst
The change merely consists of a simplification of the installation from the sources with some minor corrections. It also adjusts the style of code blocks to shell type when appropriate.
=> Install from source simplification and shell code blocks

contents/installation.rst, contents/introduction.rst
https://github.com/ethersphere/swarm-guide/issues/66
=> Simplify introduction and update install 

contents/ens.rst, contents/gettingstarted.rst, contents/up-and-download.rst
=> Docs overhaul aron - small fixes only

contents/mru.rst
Just a small clarification that the returned values are from commands doing GET requests.
=> Update explanation of culr commands retrn values in MRU section

contents/installation.rst
otherwise it looks like one long weird GO command :)
=> Fix missing code-block

contents/configuration.rst, contents/introduction.rst
=> redocumented configuration params, small refinements to intro section

contents/gettingstarted.rst, contents/up-and-download.rst
as discussed in gitter @justelad
=> Doc fixes aron june28

contents/usage/mru.rst
The MRU section of the documentation has been updated to reflect the changes introduced in https://github.com/ethersphere/go-ethereum/pull/784
=> Mru doc update

contents/introduction.rst
I removed a few notes that are duplicated, and paraphrased 2 sentences.
=> remove duplicated notes

contents/usage.rst, contents/usage/act.rst, contents/usage/manifests.rst
add documentation for the act feature.
resolves https://github.com/ethersphere/go-ethereum/issues/867
=> act documentation

contents/configuration.rst, contents/up-and-download.rst, contents/usage/act.rst
this PR adds documentation to ACT password flag and the documentation to the auto detection of default path
=> add act password and default path detection documentation

contents/usage/fuse.rst
=> Cmd swarm fs do not require ipcpath

Dockerfile
=> Dockerfile: add sphinx-tabs

contents/gettingstarted.rst, contents/installation.rst, contents/introduction.rst
1. Updated source code location and repo to ethersphere/swarm
2. Removed reference to `--nodiscover` - there is no such flag anymore.
=> update new source code location

contents/architecture.rst
This reverts commit 78f37f0248da405c7755f30b3b19423c5797001a.
=> Revert "Update architecture.rst"
